// Package entity provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package entity

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	Limit  *int64 `json:"limit,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// SearchParams defines model for SearchParams.
type SearchParams struct {
	Limit  *int64  `json:"limit,omitempty"`
	Offset *int64  `json:"offset,omitempty"`
	Search *string `json:"search,omitempty"`
	SortBy *string `json:"sort_by,omitempty"`
}
